version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/db:/app/db
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC

  frontend:
    build:
      context: ./frontend/todo
    ports:
      - "3000:80"
    depends_on:
      - backend 